Repository Nekroze/dab, pull requests merged in 2019-02, with the labels that each got.

#276 Add burrow app to monitor kafka lag
  app/docker/configs/docker-gen/templates/telegraf.conf.tmpl
  app/docker/docker-compose.burrow.yml
Labels: enhancement

#279 Fix discovering dependencies for apps with hyphenated names
  app/lib/docker.sh
Labels: bug

#280 Disable elasticsearch authentication
  app/docker/docker-compose.elasticsearch.yml
Labels: Tweak

#309 Fix ansible docker-compose install and run as default user
  app/docker/Dockerfile.ansible
  app/docker/docker-compose.ansible.yml
Labels: Tweak, bug

#311 Revoke home access for ansible
  app/docker/docker-compose.ansible.yml
Labels: Tweak

#314 Better sudo support increment
  README.md
  app/subcommands/tip
  dab
Labels: Tweak

#315 Switch tour comments to display like commands, no more backspacing
  app/tour.asciinema.json
  scripts/generate-tour.sh
  tests/tour.sh
Labels: optimization

#322 Add network recreate and its aliases to shell completion
  completion/main.go
Labels: bug

#336 Add description to stable update pr script
  scripts/request-stable-update.sh
  tests/dangerfile.js
Labels: Tweak
